<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />

  <!-- box -->
  <xacro:property name="box_size" value="0.05" />

  <!-- AGV Base -->
  <xacro:property name="agv_base_height" value="0.4" />
  <xacro:property name="agv_base_lift" value="0.025" />
  <xacro:property name="agv_base_width" value="0.495" />
  <xacro:property name="agv_base_length" value="0.73" />
  <xacro:property name="agv_base_mass" value="40" />
  <xacro:property name="agv_wheel_height" value="0.07825" />

  <!-- Macro for calculating inertia of cube -->
  <xacro:macro name="cuboid_inertia" params="m w d h">
    <inertia  ixx="${m*(h*h+d*d)/12}" ixy = "0" ixz = "0"
              iyy="${m*(w*w+d*d)/12}" iyz = "0"
              izz="${m*(w*w+h*h)/12}" /> 
  </xacro:macro>


  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- Wheel Macro -->
  <xacro:include filename="$(find ghost)/urdf/omni_wheel.urdf.xacro" />

  <!-- WHEELS -->
  <xacro:omni_wheel_250 name="wheel_front_left" parent="agv_base_link">
    <origin xyz="0.22 0.21 ${-agv_base_height/2-agv_base_lift + agv_wheel_height}" rpy="0 0 0" />
  </xacro:omni_wheel_250>
  <xacro:omni_wheel_250 name="wheel_front_right" parent="agv_base_link">
    <origin xyz="0.22 -0.21 ${-agv_base_height/2-agv_base_lift + agv_wheel_height}" rpy="0 0 0" />
  </xacro:omni_wheel_250>
  <xacro:omni_wheel_250 name="wheel_back_left" parent="agv_base_link">
    <origin xyz="-0.22 0.21 ${-agv_base_height/2-agv_base_lift + agv_wheel_height}" rpy="0 0 0" />
  </xacro:omni_wheel_250>
  <xacro:omni_wheel_250 name="wheel_back_right" parent="agv_base_link">
    <origin xyz="-0.22 -0.21 ${-agv_base_height/2-agv_base_lift + agv_wheel_height}" rpy="0 0 0" />
  </xacro:omni_wheel_250>

  <!-- AGV_BASE_LINK -->
  <joint name="base_footprint_agv_base_joint" type="fixed">
    <origin xyz="0 0 ${agv_base_height/2+agv_base_lift}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="agv_base_link" />
  </joint>
  <link name="agv_base_link">
   <inertial>
     <mass value="${agv_base_mass}" />
     <origin xyz="0 0 ${-agv_base_height/2-agv_base_lift}" />
     <cuboid_inertia m="${agv_base_mass}" d="${agv_base_length}" w="${agv_base_width}" h="${agv_base_height}" />
   </inertial>
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${agv_base_length} ${agv_base_width} ${agv_base_height}" />
      </geometry>
      <material name="White" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${agv_base_length} ${agv_base_width} ${agv_base_height}" />
      </geometry>
    </collision>
  </link>
  
  <!-- AGV lidar -->
  <joint name="base_footprint_lidar_joint" type="fixed">
    <origin xyz="0.13 -0.0015 0.46" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="agv_lidar" />
  </joint>
  <link name="agv_lidar">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${box_size} ${box_size} ${box_size}"/>
      </geometry>
      <material name="Blue" />
    </visual>
  </link>

  <gazebo reference="agv_lidar">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <sensor type="ray" name="agv_lidar1">
      <pose>${box_size/2} 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>600</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>721</samples>
            <resolution>1</resolution>
            <min_angle>-${M_PI}</min_angle>
            <max_angle>${M_PI}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>20.0</max>
          <resolution>0.001</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_agv_lidar_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>agv_lidar</frameName>
      </plugin>
    </sensor>
  </gazebo>
  
  <gazebo>
    <!-- <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so"> -->
    <plugin name="planar_move_controller" filename="libgazebo_ros_planar_move.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <odometryRate>600.0</odometryRate>
      <publishTF>true</publishTF>
    </plugin>
  </gazebo> 

</robot>
