axis_linear_x: 1  # Left thumb stick vertical
axis_linear_y: 0  # Left thumb stick horizontal
scale_linear: 0.3
scale_linear_turbo: 0.9

axis_angular: 3  # Right thumb stick horizontal
scale_angular: 1
scale_angular_turbo: 0.9

enable_button: 5  # R1 button
enable_turbo_button: 5  # R2 button

start_button: 7
